### ISSUE TITLE
Enable Testing of Policies

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#12]
We need to consider how Policy admins will test their Policies.

Per @joeduffy:

We should definitely think about how people will test their rules. I _think_ the answer is, "it's just code, write some tests." But that wasn't the answer for our IaC offering for some subtle reasons, so I wanted to call this out as an explicit use case to think about. Clearly if people are trusting security/compliance/etc to this tool, they will want to test it. Sentinel goes way out of their way on this: https://docs.hashicorp.com/sentinel/writing/testing. This doesn't need to be in the MVP, of course.

**Comment by joeduffy** [comment]
I _thought_ there would be a simple way to accomplish this, but I was foiled! Thankfully I think there are probably a small number of things we can do that will get us to a reasonable place.

I began by factoring my rules so that the raw check functions themselves were exported:

```typescript
import * as aws from "@pulumi/aws";
import { PolicyPack, typedRule } from "@pulumi/policy";
import { ResolvedResource as R } from "@pulumi/pulumi/queryable";
import * as assert from "assert";

export async function checkCmkBackingKeyRotationEnabled(
        it: R<aws.kms.Key>): Promise<void> {
    assert(it.enableKeyRotation, "expected key rotation to be enabled (enableKeyRotation: true)");
}

export const policies = new PolicyPack("awsguard", {
    policies: [
        {
            name: "cmk-backing-key-rotation-enabled",
            enforcementLevel: "advisory",
            rules: typedRule(aws.kms.Key.isInstance, checkCmkBackingKeyRotationEnabled),
        },
    ],
});
```

I then attempted to write a unit test `tests/checkCmkBackingKeyRotationEnabled.spec.ts`:

```typescript
import * as aws from "@pulumi/aws";
import { expect } from "chai";
import { ResolvedResource as R } from "@pulumi/pulumi/queryable";
import { checkCmkBackingKeyRotationEnabled } from "../";

describe("#checkCmkBackingKeyRotationEnabled", () => {
    const emptyKey: R<aws.kms.Key> = {} as any;

    it("Should reject enableKeyRotation of undefined, null, and false", async () => {
        expect(() => checkCmkBackingKeyRotationEnabled(emptyKey)).to.throw();
        expect(() => checkCmkBackingKeyRotationEnabled(Object.assign(emptyKey, { enableKeyRotation: undefined }))).to.throw();
        expect(() => checkCmkBackingKeyRotationEnabled(Object.assign(emptyKey, { enableKeyRotation: null }))).to.throw();
        expect(() => checkCmkBackingKeyRotationEnabled(Object.assign(emptyKey, { enableKeyRotation: false }))).to.throw();
    });

    it("Should accept enableKeyRotation of true", async () => {
        expect(() => checkCmkBackingKeyRotationEnabled(Object.assign(emptyKey, { enableKeyRotation: true }))).to.not.throw();
    });
});
```

This would give me way more confidence that my rule handles all of the edge cases. (For this particular rule, it's not a big deal, but for many of the ones I'm trying to implement, they can get rather complicated!)

Unfortunately, something to do with https://github.com/pulumi/pulumi-policy/issues/88 causes the process to hang and never exit.

It does raise the question of whether this is a valid way to test my code, for many of the same reasons `PULUMI_TEST_MODE` didn't work (and we had to instead pursue options like https://www.pulumi.com/blog/unit-testing-infrastructure-in-nodejs-and-mocha/).

**Comment by ekrengel** [comment]
@justinvp is this done now that we have stack validation helpers for our unit tests? Or is there something else missing?

**Comment by justinvp** [comment]
@ekrengel, yep, this is done! We've demonstrated how to test policies in awsguard. Closing.

**Comment by XuejiaoZhang** [comment]
@justinvp @ekrengel 
Hi, I have a question to ask, for Typescript, as you said we can refer to awsguard for the testing method. I'm wondering for Python and OPA (CrossGuard integrated with OPA), where could we get some examples for references? Or do you have some recommendations? Thanks in advance.

**Comment by emiliza** [comment]
Hi @XuejiaoZhang - OPA is still in _preview_ mode and so our examples coverage there is lacking.  We do have some python policy examples though, not OPA, if you want to give that a shot: https://github.com/pulumi/examples/tree/master/policy-packs

**Comment by XuejiaoZhang** [comment]
@emiliza  Thanks for your reply. What I mean is testing examples for policy written in Python.
