### ISSUE TITLE
Provide easier type checking

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#158]
_This may belong in @pulumi/pulumi but opening this in @pulumi/pulumi-policy since this Policy is the specific need/use case for it._

When doing stack validations you often (always?) need to check a resource's type. Currently, this involves something like this:
```ts
if (args.type === "azure:storage/account:Account") { /* ... */ }
```

We should provide an easier mechanism for doing this similar to our `isInstance(o)` method that doesn't require the user to know or learn the type's string value.

Related to #84.

**Comment by ekrengel** [comment]
Cool cool! I also had a similar use case here, where I was creating a stack validation policy for dynamodb resources.. Dont judge the policy too much its still a WIP 😆 

```
/**
 *
 * @param [enforcementLevel="advisory"] The enforcement level to enforce this policy with.
 */
export function dynamodbTableAutoscalingEnabled(
    enforcementLevel: EnforcementLevel = "advisory"): StackValidationPolicy {
    return {
        name: "dynamodb-autoscaling-enabled",
        description: "Checks whether Auto Scaling or On-Demand is enabled on your DynamoDB tables " +
            "and/or global secondary indexes.",
        enforcementLevel: enforcementLevel,
        validateStack: (args: StackValidationArgs, reportViolation: ReportViolation) => {
            const dynamodbTables = getResolvedResources(aws.dynamodb.Table.isInstance, args);
            const appScalingPolicies = getResolvedResources(aws.appautoscaling.Policy.isInstance, args);
            const policyResourceIDMap: Record<string, q.ResolvedResource<aws.appautoscaling.Policy>> = {};
            for (const policy of appScalingPolicies) {
                policyResourceIDMap[policy.resourceId] = policy;
            }

            for (const table of dynamodbTables) {
                if (policyResourceIDMap[table.id] === undefined) {
                    reportViolation(`DynamoDB table ${table.id} missing appscaling policy.`);
                }
            }
        },
    };
}

// Utility method for defining returning all resources matching the provided type.
function getResolvedResources<TResource extends Resource>(
    typeFilter: (o: any) => o is TResource,
    args: StackValidationArgs,
): q.ResolvedResource<TResource>[] {
    return args.resources
        .map(r => (<unknown>{ ...r.props, __pulumiType: r.type } as q.ResolvedResource<TResource>))
        .filter(typeFilter);
}
```

**Comment by justinvp** [comment]
We've also included a helper along the lines of `validateTypedResource`, but for stack validation in [`awsguard`](https://github.com/pulumi/pulumi-awsguard/blob/612bf9ece3f5d07aa5f3e010b0a673b109bc4657/src/security.ts#L170-L184):

```typescript
function validateTypedResources<TResource extends Resource>(
    typeFilter: (o: any) => o is TResource,
    validate: (
        resources: q.ResolvedResource<TResource>[],
        args: StackValidationArgs,
        reportViolation: ReportViolation) => Promise<void> | void,
): StackValidation {
    return (args: StackValidationArgs, reportViolation: ReportViolation) => {
        const resources = args.resources
            .map(r => (<unknown>{ ...r.props, __pulumiType: r.type } as q.ResolvedResource<TResource>))
            .filter(typeFilter);
        validate(resources, args, reportViolation);
    };
}
```

Some additional thoughts:

- At a minimum, we need a helper like Erin's to enable doing multiple filters inside a single validation rule. But we may still want to add something like we have in `awsguard` that can be used for simple rules that only are filtering on a single kind of resource.
- We should probably use the same approach as `validateTypedRule` now uses that doesn't require having to pass `isInstance` (instead, you just pass the type, and we lookup `isInstance` as an implementation detail).
- Instead of using `ResolvedResource<T>` we may want to define our own variant. `ResolvedResource` [excludes](https://github.com/pulumi/pulumi/blob/f7f4333909876bd9b0a3e1a4e66d7da81243a813/sdk/nodejs/queryable/index.ts#L23) the `urn` and `getProvider` properties from the resource type, but we should keep `urn`, [now that we allow reporting the `urn` of the resource that violates the policy](https://github.com/pulumi/pulumi-policy/pull/151). But we're also now exposing the `name`, and plan to expose more data about each resource like the resource options. It would be good to be able to easily get this associated data for a resource that's been filtered down and made more strongly typed.

**Comment by clstokes** [comment]
Adapting from `validateTypedResource(...)` I was able to come up with the below helper method for my immediate need but this should still be a built-in helper.

```ts
const isType = function <TResource extends Resource, TArgs>(
    actual: string,
    expected: { new(name: string, args: TArgs, ...rest: any[]): TResource; }
): boolean {
    return actual === (<any>expected).__pulumiType;
}
```

**Comment by justinvp** [comment]
PR is here: https://github.com/pulumi/pulumi-policy/pull/173
Just need to finalize on naming. Moving this to M31 since this isn't blocking M30, but will close today or tomorrow.
