### ISSUE TITLE
Pulumi policy v1.11.0 treated as resource plugin and fails to install with python

### ISSUE THREAD

**Issue by stooj** [pulumi/pulumi-policy#356]
### What happened?

When I run the `pulumi plugin install` command for a project with `pulumi-policy`, the command tries to install `pulumi-policy` as a resource plugin and fails.

### Example

Error message:
```
pulumi plugin install                                                           ─╯

[resource plugin pulumi_policy-1.11.0] installing
error: [resource plugin pulumi_policy-1.11.0] downloading from : failed to download plugin: pulumi_policy-1.11.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-pulumi_policy-v1.11.0-linux-amd64.tar.gz
```

To reproduce:

```
pulumi new -y gcp-python
echo "pulumi-policy" >> requirements.txt
venv/bin/pip install -r requirements.txt
pulumi plugin install
```

This issue is not present in v1.10.0.

It happens with poetry as well.

I was not able to reproduce this using Typescript, so I think it's limited to python projects.

### Output of `pulumi about`

```
CLI
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  gcp            7.30.1
resource  pulumi_policy  1.11.0
language  python         unknown

Host
OS       nixos
Version  24.05 (Uakari)
Arch     x86_64

This project is written in python: executable='/home/stooj/code/pulumi/stooj/pulumi-support/5480/policy6/venv/bin/python' version='3.11.9'

Current Stack: stooj/5480-6/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/stooj
User           stooj
Organizations  stooj, team-ce, higara, demo
Token type     personal

Dependencies:
NAME                    VERSION
aiodns                  3.2.0
aiohttp                 3.9.5
asn1crypto              1.5.1
async-timeout           4.0.3
awscli                  2.15.43
azure-cli               2.60.0
azure-loganalytics      0.1.1
azure-mgmt-common       0.20.0
azure-mgmt-consumption  10.0.0
azure-mgmt-relay        1.1.0
azure-storage-blob      12.19.1
bcdoc                   0.16.0
black                   24.4.0
botocore                1.34.87
Brotli                  1.1.0
brotlicffi              1.1.0.0
curio                   1.6
Jinja2                  3.1.4
pbr                     6.0.0
pip                     24.1.2
poetry                  1.8.3
pulumi_gcp              7.30.1
pulumi_policy           1.11.0
pyasn1                  0.6.0
python-socks            2.4.4
redis                   5.0.3
ruamel.base             1.0.0
setuptools              69.5.1.post0
trio                    0.25.0
wheel                   0.43.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This is the same underlying reason as https://github.com/pulumi/pulumi/issues/15536 and is due to a behavior change in v69.0.3 and later of `setuptools`.

Comparing the content of the two `.whl` files downloaded from PyPi for v1.10.0 vs. v1.11.0:

<img width="1003" alt="Screenshot 2024-07-12 at 4 57 44 PM" src="https://github.com/user-attachments/assets/30e1b630-5046-413d-919e-7f1a80d482a6">

v1.10.0 has a name of `pulumi-policy` whereas v1.11.0 is now `pulumi_policy`.

Note that we do have a mechanism for a package to indicate it doesn't have an associated plugin: the package can include a `pulumi-plugin.json` file with `{ "resource": false }`. However, for a brief period of time the file we looked for was originally called `pulumiplugin.json`. It was renamed to `pulumi-plugin.json` in https://github.com/pulumi/pulumi/pull/8593 when it was going to actually be used more broadly. However, `pulumi-policy` is still using the [old name](https://github.com/pulumi/pulumi-policy/blob/09ce176c9e7524872f412a22932c32980ec8a70c/sdk/python/lib/pulumi_policy/pulumiplugin.json
).

This hasn't mattered because there is an explicit [exemption](https://github.com/pulumi/pulumi/blob/5ae05fefc2a715ad7f429c1b4da422170235d114/sdk/python/cmd/pulumi-language-python/main.go#L428-L430) for `pulumi-policy` in the code that looks for plugins in the Python language host for even older versions of `pulumi-policy` that didn't have a `pulumiplugin.json` file. Which is what has been preventing the plugin install attempts until now for v1.10.0 and earlier. But now that exception is no longer working because of the name change due to the `setuptools` behavior change.

So there are two fixes here:

1. Rename `pulumiplugin.json` to `pulumi-plugin.json` in `pulumi-policy` and release a new version.
2. Fix-up the Python language host to exclude both `pulumi_policy` and `pulumi-policy`.
