### ISSUE TITLE
Idea: allow user-specified tag for policy version

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#41]
The version number returned by `publish` and then used by `apply` is opaque and not very intuitive. 

Could we allow users to specific a tag for the version and then use that for the apply? I’m thinking similar functionally to git tags. That way users can specify a version or even a git aha as their tag to make it more meaningful.

**Comment by ekrengel** [comment]
@hausdorff I believe this is something we have NOT slotted for GA correct? If so, I'll take the milestone off of this.

**Comment by lukehoban** [comment]
Where did we end up on this?  I do continue to believe that a simple versioning model based on what's in `package.json` (or whatever other language packaging exists) is a significantly simpler and more "normal" story for users than a monotonically increasing number outside of the users control.  It seems like most new users of policy have also noted the same thing.  Any reason *not* to adopt this for GA?

**Comment by justinvp** [comment]
I must admit, I am not a huge fan of the monotonically increasing number and would love to improve this for GA. @ekrengel, let's chat about this in our meeting this afternoon.

**Comment by ekrengel** [comment]
Trying to get a better idea of how much work this would be so going to outline what we would need to go:

* Update service to have a `ext_version` column for the `PolicyPacks` table and update all APIs to also accept the `ext_version` -- if its an `ext_version` we will prepend if w a `v` in the path (e.g. `/policypack/test/versions/1` vs `/policypack/test/versions/v1.0.1`) ---> Medium
* Update frontend to use `ext_version` as appropriate ---> Small
* Update the CLI to get and create PP with the version from `package.json` ---> Small
* Update CLI gestures to allow for use of `ext_version` and docs ---> Medium

Total work is about 12 points. 

----

Similar to npm, we would not allow a version to be reused.  From [npm publish docs](https://docs.npmjs.com/cli/publish)

> Once a package is published with a given name and version, that specific name and version combination can never be used again, even if it is removed with npm-unpublish.

**Comment by chrsmith** [comment]
I'm highly confident that we can figure out how to migrate our current notion of "version" to a more robust one, such as what NPM uses. What you've listed @ekrengel looks about right, but I wouldn't be surprised if (1) it's missing _something_ and (2) we'd figure it out when we came across it.

I won't try and argue that we shouldn't go with the more common notion of version from NPM. I'll just highlight some of the concerns that lead us to starting with the monotonically increasing version to get the ball rolling.

Are we sure we know all of the invarints we need to enforce service side, beyond just preventing reuse of a (name x version)? Should we require they adhere to some fixed format? (e.g. `^\d+\.\d+\.\d+[-\w+]?$`) When you "apply the latest policy pack version", do we know what that will mean once we allow user-specified values?

We can take inspiration from NPM, sure. But we'd also be imposing those same semantics to other programming languages and their package managers that are used for PAC too. For example, can we can for certain that the same version naming convention and requirements is the same for PIP, Nuget, and Golang? (I'd assume that probably is the case, but we may want to confirm that before we start enforcing some rules that would make it a pain to interface with from other languages.)

I feel bad since I'm the one who nudged us into using the numeric versioning scheme we have today, which is universally hated. So I'm happy to help out in refactoring things to support a better system once we are sure we know what it is.

**Comment by ekrengel** [comment]
This is now implemented in pulumi/pulumi, pulumi/policy, and the service. Although it is not release yet in pulumi/pulumi and /policy.
