### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#87]
Here are a few bits of API feedback. I'll add more as I go:

- It's odd that `rules` can have a single rule, since the property name is plural. Any reason not to just have a `rule` property for the singular case (which I assume will be most common)?

- `enforcementLevel` is a mouthful. Furthermore, I find it odd to define enforcement level on the policy rule _definition_, rather than its _application_. Should we just call this `severity`?

- I find the `typedRule` construct a bit awkward to interact with. Instead of

    ```typescript
    rule: typedRule(aws.s3.Bucket.isInstance, bucket => {}),
    ```

    is there any way it could be something like this instead?

    ```typescript
    rule: new Rule<aws.s3.Bucket>(bucket => {}),
    ```

**Comment by hausdorff** [comment]
```typescript
rule: new Rule<aws.s3.Bucket>(bucket => {}),
```

How would this work? You need the `isInstance` to perform the filter objects, right? You might be able to do something like (this is pseudocode) `Rule<T implements { isInstance: (o: any) => o is T }>` but I have not tried this to see if it would work.

**Comment by hausdorff** [comment]
> It's odd that `rules` can have a single rule, since the property name is plural. Any reason not to just have a `rule` property for the singular case (which I assume will be most common)?

I am not opposed to this if everyone thinks this is more user-friendly, but I think it's weird to have two fields for rules, and I don't know what the behavior should be if you set both `rules` and `rule`.

**Comment by hausdorff** [comment]
> `enforcementLevel` is a mouthful. Furthermore, I find it odd to define enforcement level on the policy rule _definition_, rather than its _application_. Should we just call this `severity`?

We put this on the `Policy` itself because (1) it's more annoying to have to set them all in the console, and (2) other systems include it in the rule definition—but, eventually, when we have config values, we will make this overridable.

As for me, I'm not sure what `severity` means if it's not an enforcement level. Again—whatever people find more intuitive, but I personally prefer `enforcementLevel`.

also cc @clstokes and @ekrengel on all of the above.

**Comment by joeduffy** [comment]
> I think it's weird to have two fields for rules

Personally, I think it's weirder to have a property named `rules` that accepts a single rule!

> I'm not sure what severity means if it's not an enforcement level. Again—whatever people find more intuitive, but I personally prefer enforcementLevel.

Enforcement level is something decided on the application of a policy pack, not the definition of one. The current setup feels a bit bizarre to me. I suppose it could be `suggestedEnforcementLevel`, but I do suspect it's better to tease out the notion of "severity" from "enforcement" -- and then it becomes a matter of enforcing errors as mandatory, etc. This is fairly common with static analysis tools.

**Comment by clstokes** [comment]
I'm indifferent to the `rules` field accepting one rule or an array. It gave me a "Hmm?" moment at the very start but then immediately was a non-issue. I think it would be awkward to have two fields, so _if_ we're going to do a change I'd suggest we just make it `rules` that accepts an array and users can just provider an array with a single rule.

As for `enforcementLevel`, I think we should spend a good bit of time on the design discussion of parameterized/configurable rules before making any changes here. We'll need to strike a balance between the _as Code_ part of defining everything in code and being very deterministic/predictable with adjusting values via the UI and providing the end users with adequate information about the policies and their state as they're executed.

**Comment by ekrengel** [comment]
I would say the having `rules` accept a single rule or an array is a common pattern we use in the awsx stuff as well.

**Comment by hausdorff** [comment]
If we really don't like the way it is now, I think we should just make `rules: Rule[]` rather than `rules: Rule | Rule[]`. Having separate properties for `rule` and `rules` does not seem great to me.

**Comment by hausdorff** [comment]
Going back to the original feedback:

1. Is consistent with how we do awsx, so I propose we keep as is.
1. I agree with Cameron and propose we do nothing for now.
1. I _think_ this is unfixable as it exists now. I'd love to fix it if it is, but I don't see a way to. If no on else has suggestions, I think we'll have to leave it as is.

**Comment by hausdorff** [comment]
Given all that, I think we should consider closing out the issue. @joeduffy ?

**Comment by hausdorff** [comment]
I'm going to close this out, then. Please reopen if we need to discuss more.

**Comment by chrsmith** [comment]
This definitely needs some revision. I hit the same issue trying to develop PAC, and there are many things that aren't intuitive.

**Comment by chrsmith** [comment]
After spending some time trying to implement PAC rules, there are a few things that seem odd enough to warrant a breaking change. Here's the set of problems I see, as well as some suggested improvements. (Though I'd also be in favor of renaming `enforcementLevel` to `severity` as well, but that's a less invasive issue.)

@justinvp what do you think of these changes to the API?

---

# PAC SDK API Changes

## Replace `Policy.rules` with `Policy.validates`

There are many problems with the way you provide the implementation of a policy.
Currently you specify one or more `policy.Rule` values, which will then be executed
to do the actual validation.

```ts
export interface Policy {
    ...


    rules: Rule | Rule[];
}

export type Rule = (type: string, properties: any) => void;

export function typedRule<TResource extends pulumi.Resource>(
    filter: (o: any) => o is TResource,
    rule: (properties: q.ResolvedResource<TResource>) => void,
): Rule {
    ...
}
```

- Having `rules` plural, but accept a single value or an array is confusing.
- In practice, it seems like supplying multiple "rules" is more cumbersome than
  a single rule, with multiple statements.
- It doesn't provide a way to extend to support other ty pes of validations, such
  as rules which need to inspect all resources at the end of a stack update.

As an alternative, I suggest we replace `policy.Rule` with a different type, though
the general semantics will remain the same:

```diff
export interface Policy {
    ...


    /**
     * The provided validator will inspect resource(s) during the stack update and
     * report policy failures as they are observed.
     *
     * Typically a validator would be created via `resourcesByType` or `allResources`.
     */
    validates: Validator;
}

// NB. This should be something much closer to `pulumi.Resource`, see
// later in this document for a proposed change.
type PolicyResource = { type: string, properties: any };

/**
 * A Validator provides the implementation for checking that stack resources conform
 * to a given policy. Each function will be called as stack resources are processed,
 * a policy violation will be reported if they return a `string` value, returning
 * `undefined` in the event that no violations are found.
 */
export interface Validator {
    validateResource(type: string, properties: any): string | undefined;
    validateAllResources(allResources: PolicyResource[]): string | undefined;
}

/**
 * resourcesByType provides a convenient shorthand for creating a resource validator that
 * is only ran against Pulumi resources of a specific type.
 *
 * Example:
 * ```
 * import * as assert from "assert";
 * import * as aws as "@pulumi/aws";
 *
 * typedRule(aws.s3.Bucket.isInstance, (s3Bucket: any) => {
 *    if (it.acl === "public-read") {
 *          return `The S3 bucket s3://${s3Bucket["name"]} is public.`;
 *    }
 *    return undefined;
 * });
 * ```
 *
 * @param filter is a type guard, verifying the provided value is an instance of the
 * type the resource the policy whishes to inspect. Typically Pulumi libraries have
 * a static method `isInstance()` defined on resource types that can be used for
 * this purpose.
 * @param fn the callback to perform the validation. Returning a human-friendly
 * description of any policy violations encountered.
 */
export function resourcesByType<TResource extends pulumi.Resource>(
    filter: (o: any) => o is TResource,
    fn: (properties: all) => string | undefined,
): Validator {
    ...
}

/**
 * allResources provides a convenient shorthand for constructing a Validator that will
 * execute on all resources within the Pulumi stack at the end of the preview/update operation.
 *
 * The provided function will be executed, and will report any policy violations by returning
 * a human-friendly string. Or `undefined` if no violations are found.
 */
export function allResources(fn: (allResources: PolicyResource[]) => string | undefined): Validator {
    ...
}
```

## Return `string` and not Throw `AssertionError`

It looks like we vacillated on this aspect of the design, but the semantics of
having policy implementations throw an exception of type `AssertionError` to
report violations seems like the wrong choice.

- It's counter-intuitive. If just looking at the type signature, it isn't clear at all
  how a `Validator`/`policy.Rule` would report an error.
- And if you did happen to throw an exception, unless it is specifically an `AssertionError`,
  it would be interpreted as a runtime failure and not a policy violation.
- The NodeJS assertions library includes superfluous information in the error, such as
  `"expected value 'true' to == 'false'"`.
- Throwing exceptions for unexceptional conditions -- e.g. if a resource is in a
  known, invalid state -- is generally an anti-pattern. (As exceptions in some languages
  incur significant performance hits, and make code more difficult to follow.)

A seemingly much more natural way to express this would be to have policy implementations
return `string | undefined`, or even a `policy.Result` type (which could, for example
act like an `Option<string>`).

## Wire through more Pulumi-isms into the Surface Area

The current implementation of PAC only marshals the Pulumi resource's output properties
to the policy pack process. This does cover the 90% case, but prevents us from writing certain classes of reasonable policies, which would require the `URN` and handle to the resource provider.

For example:

- Verifying that all resources are created within a specific AWS account. e.g.
  "production" stacks must all put their resources in the "production" AWS account.
- Enforcing naming rules for Pulumi resources.
- Verifying that client-side encryption is used, and secrets are not stored in the
  Pulumi Service. (This actually relies on the `Deployment`/`Snapshot`, rather than
  an individual `Resource`, but it's the same class of issue.)

To be honest, I'm not 100% sure what we can do here, perhaps it's just a matter of supporting a validator where the callback is presented with the URN, the resource, and the resource's provider's outputs.

**Comment by ekrengel** [comment]
Chris and I chatted about these suggestions this morning, but I will also leave my thoughts here.

* I am wondering is `isValidResource` > `validateResource` would make it clearer to Policy authors what the function is suppose to return. Chris brought up that to return use mutli value return in TS we would likely need to return an object which would complicate things.
*  Wire through more Pulumi-isms -- I believe there are number of issue open for things like this, but necessarily the ones Chris calls out here. We should make sure we consolidate and address them all.
* I agree w writing more complex rules > multiple rules.

Overall, think this a huge step in the right direction. Thanks for doing this @chrsmith
